[package]
name = "stardust-xr-molecules"
version = "0.51.0"
edition = "2024"

authors = ["Nova King <technobaboo@proton.me>"]
description = "Widget library for Stardust XR, built on top of Fusion"
license = "MIT"
repository = "https://github.com/StardustXR/molecules/"
homepage = "https://stardustxr.org"

[workspace]
members = ["protocols"]

[dependencies]
glam = { version = "0.29.0", features = ["mint"] }
lazy_static = "1.4.0"
rustc-hash = "2.1.1"
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["rt"] }
tracing = "0.1.40"
lerp = "0.5.0"
shiva-color-rs = "0.0.1"

[dependencies.stardust-xr-fusion]
version = "0.51.0"
git = "https://github.com/StardustXR/core.git"
branch = "binder"

[dependencies.stardust-xr-protocol]
version = "0.51.0"
git = "https://github.com/StardustXR/core.git"
branch = "binder"

[dependencies.stardust-xr-molecules-protocols]
path = "protocols"

[dependencies.gluon]
git = "https://github.com/technobaboo/gluon"

[dev-dependencies]
tokio = { version = "1.38.0", features = ["full"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies.pion-binder]
git = "https://github.com/technobaboo/pion"
