[package]
name = "stardust-xr-molecules-protocols"
version = "0.1.0"
edition = "2024"

[features]
default = []
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0.228", optional = true }
tracing = "0.1.44"

[dependencies.stardust-xr-protocol]
git = "https://github.com/StardustXR/core.git"
branch = "refactor/strongipc"

[dependencies.gluon]
git = "https://github.com/technobaboo/gluon"
branch = "refactor/strongipc"


[build-dependencies.gluon-codegen]
git = "https://github.com/technobaboo/gluon"
branch = "refactor/strongipc"
[build-dependencies.stardust-xr-protocol]
git = "https://github.com/StardustXR/core.git"
branch = "refactor/strongipc"
