[package]
name = "stardust-xr-molecules-protocols"
version = "0.52.0"
edition = "2024"

[features]
default = []
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0.228", optional = true }
tracing = "0.1.44"

[dependencies.gluon-ipc]
version = "0.1.0"
# git = "https://github.com/StardustXR/gluon"

[dependencies.stardust-xr-protocol]
version = "0.52.0"
# git = "https://github.com/StardustXR/core.git"


[build-dependencies.gluon-ipc-codegen]
version = "0.1.0"
# git = "https://github.com/technobaboo/gluon"
[build-dependencies.stardust-xr-protocol]
version = "0.52.0"
# git = "https://github.com/StardustXR/core.git"
