[package]
name = "stardust-xr-molecules-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
gluon.git = "https://github.com/technobaboo/gluon"

[build-dependencies]
gluon-codegen.git = "https://github.com/technobaboo/gluon"

[build-dependencies.stardust-xr-protocol]
git = "https://github.com/StardustXR/core.git"
branch = "binder"

[dependencies.stardust-xr-protocol]
git = "https://github.com/StardustXR/core.git"
branch = "binder"
